name: RegionsInfo
main: ru.servbuy.regions.Main
author: FlamesYT
version: 2.2
depend: [WorldGuard]
commands:
  rginfo:
    description: shows information about plugin
    permission: rginfo.info
    aliases: [ri]
    usage: /rginfo
           /ri
           /ri ?
           /ri help
           /ri toggle
           /ri reload
permissions:
  rginfo.*:
    description: Gives full access to all rginfo commands
    children:
      rginfo.reload: true
      rginfo.info: true
      rginfo.toggle: true
      rginfo.see: true
  rginfo.reload:
    description: Allows you to reload plugin
    default: op
  rginfo.info:
    description: Allows you to see plugin info
    default: true
  rginfo.toggle:
    description: Allows you to toggle actionbar
    default: false
  rginfo.see:
    description: Allows you to see regions info
    default: false
